### ISSUE TITLE
Add blocklist support

### ISSUE THREAD

**Issue by sammcj** [mozilla/firefox-ios#1073]
It would be fantastic if Firefox for iOS could support adding a blocklist such as those used by the popular extension uBlock.

I would see this working as such:

- Option added to settings to paste a URL to a tgz blocklist.
- When a tgz blocklist is added to settings, it is downloaded locally and the hosts / IPs contained within are added to a blocklist similar to a hostsfile on a desktop.

**Comment by thebnich** [comment]
Filed as [bug 1210111](https://bugzilla.mozilla.org/show_bug.cgi?id=1210111). Unfortunately, `WKWebView` is not compatible with content blockers, and `SFSafariViewController` is far too restrictive. Downgrading to `UIWebView` would be the only way we'd be able to implement our own content blocking, but that would be a pretty large effort and would hurt performance. We're hoping Apple soon exposes networking APIs for `WKWebView` so that we can implement this.
