### ISSUE TITLE
Add content blocking support

### ISSUE THREAD

**Issue by iliketurtlesbro** [mozilla/firefox-ios#1271]
I believe it is possible for third party browsers to take advantage of iOS 9's content blocking capabilities as long as they use they correct Safari webview type. If this is not possible, may I suggest that you natively build in a privacy blocklist such as disconnect, so that users do not have to sacrifice their web privacy when choosing Firefox over Safari on iOS.

**Comment by thebnich** [comment]
Filed as [bug 1210111](https://bugzilla.mozilla.org/show_bug.cgi?id=1210111). Unfortunately, `WKWebView` is not compatible with content blockers, and `SFSafariViewController` is far too restrictive. Downgrading to `UIWebView` would be the only way we'd be able to implement our own content blocking, but that would be a pretty large effort and would hurt performance. We're hoping Apple soon exposes networking APIs for `WKWebView` so that we can implement this.

**Comment by LeoNatan** [comment]
For anyone interested in a private API solution (for custom builds), there is a `_userContentExtensionsEnabled` property on `WKWebView`, which enables use of system content blockers. Use `setValue:forKey:` API to set it to true.
