### ISSUE TITLE
Very slow tab closing at 100+ tabs

### ISSUE THREAD

**Issue by stek29** [mozilla/firefox-ios#1452]
As I guess, it's predrawing animation of tabs shifting. But the problem is that it's very slow when I have more than ~100 tabs
Now I have 426 tabs, and I need to wait for ~50 seconds after closing a tab.
Tab disappear, and then it hangs. 
Maybe it can be optimized or you can add another tab view mode which is comfortable at 100+ tabs.
I'm using last appstore version on iPhone 5S

BTW FF handles such amount of tabs much better than Safari (Just can't have more than ~20 tabs) and Chrome (needs huge amount of RAM and crashes).

**Comment by rnewman** [comment]
I'm honestly amazed that things still work at all, without backboard/springboard crashes. Those are page thumbnails, and each one represents a webview!

We're unlikely to do significant work to support hundreds of tabs on a phone; it's so far outside even the 99th percentile that the effort isn't worthwhile. But in this case it might be enough to disable or tweak animations in the tab tray (for which I'll file a bug, because I see this even with 9 or 10 tabs), or we might address this case with future tab interaction work.

I'm going to close this issue, and push any specifics into upstream bugs in Bugzilla. Thanks for your feedback!
