### ISSUE TITLE
How-to build in my device?

### ISSUE THREAD

**Issue by rodmoreno** [mozilla/firefox-ios#197]
I tried to compile the application directly into a device (iPhone 5) and I failed, I mark error when trying to sign the application, as it could run it on my device?

**Comment by AaronMT** [comment]
Building to device is currently restricted to internal staff. I imagine at some point in the future we may open that up. For now, using the Simulator is the best bet.

**Comment by rodmoreno** [comment]
Ok, how sad. I'll have to wait, thank you very much.

**Comment by helveticade** [comment]
Has this changed at all as release gets closer?

**Comment by rainforest1155** [comment]
Is building to device still restricted? The build instructions don't say anything about this. I'm just looking to build this for my iPad so that I'd be able to use my custom sync server as that's not a feature available in Firefox iOS yet.

I'm hoping that there's a way to still do it, e.g. by changing the appid to my own? 

Thanks!

**Comment by AaronMT** [comment]
@st3fan ^?

**Comment by st3fan** [comment]
@rainforest1155 We have instructions at https://github.com/mozilla/firefox-ios/blob/master/BUILDING.md

I would suggest to start by trying to get a build going in the Simulator. If that works then you can try to run on your own device. This does require changing bundle identifiers. But it should be possible, even with a free developer account.

**Comment by rainforest1155** [comment]
Thank you very much, that works great!
