### ISSUE TITLE
Bug 1289556 - Layout for new Activity Stream home panel 

### ISSUE THREAD

**Issue by farhanpatel** [mozilla/firefox-ios#2039]
I thought it would be a neat idea to talk about design of this bug here in the issues section. This way instead of writing a bunch of code and realizing later that my approach was incorrect we can discuss the design here and I can get feedback before I write too much code. This will also serve as a way to document the design for the future. 

![178815181](https://cloud.githubusercontent.com/assets/522281/17533714/e61083dc-5e3a-11e6-8103-2c6b98c849b7.png)

ActivityStreamPanel.swift
----

- A base class that conforms to the HomePanel protocol. This will let us use it with the existing home panels
- A UICollectionView with different types of rows for TopSites and ActivityStreamButtons. (This will be in a different issue)
- I opted for a UICollectionview because on iPad the Bookmarks/Highlights might be multi row. 
- The topSites will be a UICollectionViewCell with a UICollectionView inside itself. I'll cache the data source so that the topsites dont need to be fetched frequently as the user scrolls the ActivityStream. 

Thoughts? Anything I should look into?

**Comment by thebnich** [comment]
> The topSites will be a UICollectionViewCell with a UICollectionView inside itself.

That sounds unusual to me -- we might face some challenges with the sizing/scrolling of the outer cell. Why not flatten the structure so that all views are at the top collection view level? `UICollectionView` is flexible enough that you can define the layout on a per-cell basis. We actually did this with the original `TopSitesPanel`, where we had thumbnails at the top with a scrollable list underneath ([code here](https://github.com/mozilla/firefox-ios/blob/ad12feeb321a5829d185a44de1bd0193ae8b8456/Client/Frontend/Home/TopSitesPanel.swift#L209)).

**Comment by thebnich** [comment]
Hm, on second thought after looking through the screenshots more, nested collection views might make sense to keep the design more modular. I think your design sounds good so far -- we're essentially creating a composable list of widgets.

**Comment by farhanpatel** [comment]
The issue was that the TopsitesCell needs to be scrollable and I couldnt have it scroll independently of the ActivityStreamPanel any other way 😢  I opted for a full on UIcollectionview instead of a scrollview because I will probably end up using most of the methods from the UICollectionViewDelegate anyways. And using an action scrollview would mean I'd have to do layout by myself. UIcollectionview also has support for paging built in.

**Comment by st3fan** [comment]
Random note: using standard controls like `UICollectionView` means that things will mostly just do the right thing when it comes to accessibility and RTL support.

**Comment by farhanpatel** [comment]
The design has changed slightly. 
<img width="373" alt="screen shot 2016-08-10 at 4 16 09 pm" src="https://cloud.githubusercontent.com/assets/522281/17574398/cd76041a-5f15-11e6-85f4-47f260a5deaf.png">

ASVerticalScrollCell
----
This represents the cell with the UICollectionView inside of it. There are some interesting issues here that need figuring out. 
- There needs to be paging of the Topsites.  
- The spacing of the cell needs to be uniform. When scrolling, a small part of a cell from the previous page should not appear.  (Illustrated here http://stackoverflow.com/a/20156486 )

This is a bit trickier than it looks. There is a `pagingEnabled` property on UICollectionview but it doesnt quite get me the full way. It wont scroll a full page. For example in the picture above if there were a total of 7 items. When I scrolled I would see BBC on the second page. I think I can get around this by getting rid of all spacing between the cells and then adding the white space in the TopSiteCell itself. This will make sure I dont get partial cells between pages. And if I do some calculation for how many cells it takes to fill a single page and create empty cells for the ones missing I can always get a full page scroll. 

This will involve some convoluted height/width math to figure out proper spacing of everything. 
If anyone has any suggestions on how I can do this in a less hacky way let me know!

**Comment by farhanpatel** [comment]
I've Got the ASVerticalScrollCell working the way I wanted. You can see it here 
https://github.com/mozilla/firefox-ios/tree/farhan-bryan-topsites

**Comment by sleroux** [comment]
Couple of thoughts:

* The cell is named `ASVerticalScrollCell` but it scrolls horizontally. Should it be named `ASHorizontalScrollCell`? Maybe I'm thinking about it differently.

* Instead of using a `UICollectionView` or manually laying out the cells inside your own `UIScrollView`, a nice balance would be to use a `UIStackView` for each 'page' and add the pages to the scroll view. Unfortunately stack views are iOS 9 only. There would be some great wins here as far as reducing complexity though since you don't need to lay things out and the page abstraction works nicely with how we're presenting the cells in the UI. Maybe creating a `ASHorizontalPageView` to encapsulate the layout for now would be something we can do now and replace the implementation with a `UIStackView` in the future?

* Usually I find `UICollectionView` is a great tool for many jobs but I wonder if using a separate view for each device would simplify things greatly instead of trying to make a single UI work for both. Getting a `UICollectionView` to work like a table view can get annoying - like getting the sticky headers to work. Going with the view per device layout has some other benefits such as enforcing decoupling of the data sources/domain logic from the views. I can also see it being difficult to start building a unique experience for iPad while not causing regressions or changes to the iPhone layout. To handle cell reuse, we can also make cell wrappers and refactor the cells into their own `UIView` subclasses.

* Related to the last point, I'd also try keeping the data source/delegates into their own objects where it makes sense. The more we can break the coupling between the view and data source, the easier it will be to wrap some the data-fiddling stuff with unit tests. It'd be nice to start moving away from using UITests to validate data in the UI.

**Comment by farhanpatel** [comment]
bahaha. Of course it should be named ASHorizontalScrollCell. 😆 

I thought about using UIStackView but then I thought that I'd have to do even more hacks to get that working. There is some layout calculations that I do manually but besides that I think the UIcollectionview works well. 

I agree on separate layouts for iPad/iPhone. I didnt know sticky headers were so hard. I'll switch it to a tableview for now. And decide if UICollectionview works later. 

There will be a lot of refactoring related to delegates/datasources. I'll keep testability in mind when I decide how to approach this.
